In [28]:
#This section is importing all libraries & data used for the project

#importing all necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats

#importing the data file
data = pd.read_csv("./DataFiles/CreditCard_train.csv", header=1)
#displaying the first 10 rows of the data
data.head(10)

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0   1      20000    2          2         1   24      2      2     -1     -1   
1   2     120000    2          2         2   26     -1      2      0      0   
2   3      90000    2          2         2   34      0      0      0      0   
3   4      50000    2          2         1   37      0      0      0      0   
4   5      50000    1          2         1   57     -1      0     -1      0   
5   6      50000    1          1         2   37      0      0      0      0   
6   7     500000    1          1         2   29      0      0      0      0   
7   8     100000    2          2         2   23      0     -1     -1      0   
8   9     140000    2          3         1   28      0      0      2      0   
9  10      20000    1          3         2   35     -2     -2     -2     -2   

   ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0  ...          0          0          0         0       689         0   
1  ...       3272       3455       3261         0      1000      1000   
2  ...      14331      14948      15549      1518      1500      1000   
3  ...      28314      28959      29547      2000      2019      1200   
4  ...      20940      19146      19131      2000     36681     10000   
5  ...      19394      19619      20024      2500      1815       657   
6  ...     542653     483003     473944     55000     40000     38000   
7  ...        221       -159        567       380       601         0   
8  ...      12211      11793       3719      3329         0       432   
9  ...          0      13007      13912         0         0         0   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0         0         0         0                           1  
1      1000         0      2000                           1  
2      1000      1000      5000                           0  
3      1100      1069      1000                           0  
4      9000       689       679                           0  
5      1000      1000       800                           0  
6     20239     13750     13770                           0  
7       581      1687      1542                           0  
8      1000      1000      1000                           0  
9     13007      1122         0                           0  

[10 rows x 25 columns]

In [15]:
#displaying the columns of the data file
data.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month'],
      dtype='object')

In [10]:
# #This section is visualizing & exploring the data

# #for simplification
# output = 'default payment next month'

# #Conducting exploratory data analysis (EDA)
# cols = [ f for f in data.columns if data.dtypes[ f ] != "object"]
# #Removing irrelevant columns from the data 
# cols.remove( "ID")
# cols.remove( output )

# f = pd.melt( data, id_vars=output, value_vars=cols)
# g = sns.FacetGrid( f, hue=output, col="variable", col_wrap=5, sharex=False, sharey=False )
# g = g.map( sns.distplot, "value", kde=True).add_legend()

In [7]:
# #removing outliers using z score
# z=np.abs(stats.zscore(data))
# threshhold = 3
# print(np.where(z>3))

# data = data[(z < 3).all(axis=1)]
# data.shape

In [8]:
# plt.figure(figsize=(16,14))
# cor = data.corr()
# sns.heatmap(cor, annot=True, cmap=plt.cm.Reds)
# plt.show()

In [9]:
# #Correlation with output variable
# cor_target = abs(cor["default payment next month"])
# #Selecting highly correlated features
# relevant_features = cor_target[cor_target>0.29]
# print(relevant_features)

In [22]:
from sklearn.preprocessing import StandardScaler

bill = ['BILL_AMT1', 'BILL_AMT2', 'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6']
bill_values = data.loc[:, bill].values
target_values = data.loc[:, ['default payment next month']].values
bill_values = StandardScaler().fit_transform(bill_values)
bill_values

array([[-0.64260509, -0.64727168, -0.66984012, -0.67177126, -0.66288023,
        -0.65191478],
       [-0.65954984, -0.66684158, -0.64061403, -0.61989188, -0.60562493,
        -0.59678798],
       [-0.29399193, -0.49200571, -0.48110963, -0.44454526, -0.41516611,
        -0.38906085],
       ...,
       [-0.57420665, -0.55018959, -0.5358664 , -0.39420387, -0.38765705,
        -0.49679563],
       [-0.41340357, -0.40308131, -0.39554301, -0.03834173, -0.66288023,
        -0.65191478],
       [-0.67521444, -0.67644889, -0.64963262, -0.64094806, -0.65643383,
        -0.63127392]])

In [39]:
from sklearn.decomposition import PCA

pca_bill = PCA(n_components=2)
principalComponents_bill = pca_bill.fit_transform(bill_values)
principalDf_bill = pd.DataFrame(data = principalComponents_bill
                                , columns = ['bill_pc1', 'bill_pc2'])
print(principalDf_bill)
pca_bill.explained_variance_ratio_

       bill_pc1  bill_pc2
0     -1.611216  0.010071
1     -1.546814 -0.066453
2     -1.028676  0.013599
3     -0.233383  0.177654
4     -0.960107 -0.227755
...         ...       ...
23995  1.058638  0.135535
23996 -1.031067 -0.121125
23997 -1.198402 -0.141770
23998 -1.043755  0.152590
23999 -1.604194 -0.037400

[24000 rows x 2 columns]


array([0.90774248, 0.04974495])

In [42]:
pay = ['PAY_AMT1','PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6']
pay_values = data.loc[:, pay].values
pay_values = StandardScaler().fit_transform(pay_values)
pay_values

array([[-0.3678535 , -0.24649878, -0.30874059, -0.31871886, -0.31325859,
        -0.29435041],
       [-0.3678535 , -0.23154441, -0.24661057, -0.25152793, -0.31325859,
        -0.18090744],
       [-0.26711195, -0.20750202, -0.24661057, -0.25152793, -0.24777108,
        -0.01074299],
       ...,
       [-0.28157945, -0.17384267, -0.22797157, -0.29721776, -0.19407132,
        -0.23762892],
       [-0.16510948, -0.20908882, -0.24064609, -0.25152793, -0.31325859,
        -0.29435041],
       [-0.29485238, -0.22192745, -0.24661057, -0.28512339, -0.24777108,
        -0.23762892]])

In [46]:
pca_pay = PCA(n_components=6)
principalComponents_pay = pca_pay.fit_transform(pay_values)
principalDf_pay = pd.DataFrame(data = principalComponents_pay
                               , columns = ['pay_pc1', 'pay_pc2', 'pay_pc3', 'pay_pc4', 'pay_pc5', 'pay_pc6'])
print(principalDf_pay)
pca_pay.explained_variance_ratio_

        pay_pc1   pay_pc2   pay_pc3   pay_pc4   pay_pc5   pay_pc6
0     -0.753442  0.056474  0.016774  0.028364 -0.043054  0.062851
1     -0.650050 -0.004134 -0.014271  0.023947 -0.119676  0.078670
2     -0.500570  0.038109 -0.131170 -0.038420 -0.161752  0.055923
3     -0.560491  0.045290 -0.003965  0.025886  0.009334  0.045229
4      0.554640  0.219275  0.637498  0.538860  0.123918  1.227617
...         ...       ...       ...       ...       ...       ...
23995 -0.407177 -0.084874 -0.035315  0.049919  0.036277 -0.098074
23996 -0.581877  0.059387 -0.009436  0.068554 -0.010585  0.085266
23997 -0.573232  0.106235  0.023023  0.044355 -0.033970  0.020399
23998 -0.599453  0.009161 -0.046206  0.047729  0.102597  0.050621
23999 -0.624371  0.056763 -0.001320  0.031416 -0.038328  0.025310

[24000 rows x 6 columns]


array([0.30061902, 0.14779329, 0.14538284, 0.14006904, 0.13443381,
       0.131702  ])

### Above suggests 'amount of previous payment' cannot be reduced in dimensionality simply by PCA